version: '3.8'

services:
  nginx1:
    image: nginx:latest
    container_name: nginx_on_81
    ports:
      - "81:80"  # Host port 81 → Container port 80 in container
    # Note: The port mapping is 81:80, meaning host port 81 maps
    # to container port 80, which is the default port for Nginx.    
    volumes:
      - ./html:/usr/share/nginx/html:ro 

    restart: unless-stopped

  nginx2:
    image: nginx:latest
    container_name: nginx_on_82
    ports:
      - "82:80"  # Host port 82 → Container port 80 in container
    volumes:
      - ./html1:/usr/share/nginx/html1:ro
    restart: unless-stopped

