version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx82
    ports:
      - "82:82"
    volumes:
      - ./html1:/usr/share/nginx/html1:ro
      - ./nginx82.conf:/etc/nginx/nginx.conf:ro