version: '3.8'

services:
  nginx81:
    image: nginx:latest
    container_name: nginx81
    ports:
      - "8081:80"
    volumes:
      - ./html1:/usr/share/nginx/html1:ro
      # - ./nginx81.conf:/etc/nginx/nginx.conf:ro  
