version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"                      # Web-UI unter :8080
      - "--providers.docker=true"                  # Docker als Service-Provider
      - "--entrypoints.web.address=:80"            # HTTP-Eintrittspunkt auf Port 80
    ports:
      - "80:80"                                     # HTTP
      - "8080:8080"                                 # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Zugriff auf Docker Events
    networks:
      - web

  nginx81:
    image: nginx:latest
    container_name: nginx81
    ports:
      - "81:81"  # Host-Port 81 → Container-Port 81
    volumes:
      - ./html1:/usr/share/nginx/html:ro
      - ./nginx81.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]                                     # Host-Port 8082 → Container-Port 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx81.rule=Host(`pq.ydns.eu`)"  # Traefik leitet Anfragen mit Host=localhost weiter
      - "traefik.http.routers.nginx81.entrypoints=web"
      - "traefik.http.services.nginx81.loadbalancer.server.port=80"
    networks:
      - web
  nginx82:
    image: nginx:latest
    container_name: nginx82
    ports:
      - "82:82"  # Host-Port 82 → Container-Port 82
    volumes:
      - ./html2:/usr/share/nginx/html:ro
      - ./nginx82.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]                                     # Host-Port 8082 → Container-Port 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx82.rule=Host(`ng82.localhost`)"  # Traefik leitet Anfragen mit Host=localhost weiter
      - "traefik.http.routers.nginx82.entrypoints=web"
      - "traefik.http.services.nginx82.loadbalancer.server.port=80"
    networks:
      - web
networks:
  web: